import type { MetadataRoute } from "next";
import { absoluteUrl } from "@/lib/site";

export const dynamic = "force-static";

const AI_BOTS = [
  "GPTBot",
  "OAI-SearchBot",
  "ChatGPT-User",
  "Google-Extended",
  "Googlebot",
  "bingbot",
  "DuckAssistBot",
  "ClaudeBot",
  "Claude-SearchBot",
  "Claude-User",
  "anthropic-ai",
  "PerplexityBot",
  "Perplexity-User",
  "Bytespider",
  "CCBot",
  "cohere-ai",
  "Applebot",
  "Applebot-Extended",
  "FacebookBot",
  "meta-externalagent",
];

const DISCOVERY_ALLOW = [
  "/",
  "/ai-shopping.json",
  "/catalog.json",
  "/geo-baseline.json",
  "/entity.json",
  "/entity-profiles.json",
  "/llms.txt",
  "/llms-full.txt",
  "/ai.txt",
  "/feeds/",
  "/.well-known/ard.json",
  "/.well-known/agents.json",
  "/.well-known/agent.json",
  "/.well-known/llms.txt",
  "/.well-known/llms-full.txt",
  "/.well-known/ai.txt",
  "/.well-known/ai-shopping.json",
  "/.well-known/prices.json",
  "/.well-known/price.json",
  "/.well-known/pricing.json",
  "/.well-known/entity.json",
  "/.well-known/catalog.json",
  "/.well-known/security.txt",
  "/.well-known/security",
  "/.well-known/humans.txt",
  "/agents.json",
  "/agent.json",
  "/AGENTS.md",
  "/humans.txt",
  "/security.txt",
  "/catalog",
  "/ai-shopping",
  "/entity",
  "/geo-baseline",
  "/llms",
  "/pricing.json",
  "/prices.json",
  "/price.json",
  "/products.json",
  "/organization.json",
  "/company.json",
  "/about.json",
  "/nap.json",
  "/brand.json",
  "/offers.json",
  "/dataset.json",
  "/en/ai-shopping.json",
  "/en/catalog.json",
  "/en/entity.json",
  "/en/geo-baseline.json",
  "/en/pricing.json",
  "/en/prices.json",
  "/en/price.json",
  "/en/products.json",
  "/en/llms.txt",
  "/data/catalog.json",
  "/data/prices.json",
  "/api/catalog",
  "/api/catalog.json",
  "/api/products",
  "/api/prices",
  "/api/entity",
  "/api/ai-shopping",
  "/api/v1/prices",
  "/v1/prices",
] as const;

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [...DISCOVERY_ALLOW],
      },
      ...AI_BOTS.map((userAgent) => ({
        userAgent,
        allow: [...DISCOVERY_ALLOW],
      })),
    ],
    // Bing Host directive prefers bare hostname (no scheme).
    host: "arledscreen.com",
    sitemap: absoluteUrl("/sitemap.xml"),
  };
}
