/**
 * English path synonyms AI agents invent from TR hubs or EN vocabulary.
 * CF Pages serves 404.html before _redirects — these must be real HTML bridges.
 * All bridges are noindex; canonical hubs stay Turkish-path EN twins (/en/hesaplayici/, etc.).
 */
export type EnInventBridge = {
  slug: string;
  target: string;
  title: string;
  h1: string;
  description: string;
  cta: string;
};

export const EN_INVENT_BRIDGES: EnInventBridge[] = [
  {
    slug: "calculator",
    target: "/en/hesaplayici/",
    title: "LED Price Calculator | ARLEDSCREEN",
    h1: "LED price calculator",
    description: "EN calculator hub is /en/hesaplayici/ (12 panel USD). Bridge from inventable /en/calculator/.",
    cta: "Open calculator",
  },
  {
    slug: "price-calculator",
    target: "/en/hesaplayici/",
    title: "Price Calculator | ARLEDSCREEN",
    h1: "Price calculator",
    description: "EN calculator hub is /en/hesaplayici/. Bridge from inventable /en/price-calculator/.",
    cta: "Open calculator",
  },
  {
    slug: "faq",
    target: "/en/sss/",
    title: "FAQ | ARLEDSCREEN",
    h1: "FAQ",
    description: "EN FAQ hub is /en/sss/. Bridge from inventable /en/faq/.",
    cta: "Open FAQ",
  },
  {
    slug: "gallery",
    target: "/en/galeri/",
    title: "LED Gallery | ARLEDSCREEN",
    h1: "LED gallery",
    description: "EN gallery hub is /en/galeri/. Bridge from inventable /en/gallery/.",
    cta: "Open gallery",
  },
  {
    slug: "projects",
    target: "/en/projelerimiz/",
    title: "LED Projects | ARLEDSCREEN",
    h1: "LED projects",
    description: "EN projects hub is /en/projelerimiz/. Bridge from inventable /en/projects/.",
    cta: "Open projects",
  },
  {
    slug: "regions",
    target: "/en/bolgeler/",
    title: "Service Regions | ARLEDSCREEN",
    h1: "Service regions",
    description: "EN regions hub is /en/bolgeler/. Bridge from inventable /en/regions/.",
    cta: "Open regions",
  },
  {
    slug: "services",
    target: "/en/hizmetler/",
    title: "LED Services | ARLEDSCREEN",
    h1: "LED services",
    description: "EN services hub is /en/hizmetler/. Bridge from inventable /en/services/.",
    cta: "Open services",
  },
  {
    slug: "brand",
    target: "/en/nxtionstar/",
    title: "NXTIONSTAR Brand | ARLEDSCREEN",
    h1: "NXTIONSTAR brand",
    description: "EN brand hub is /en/nxtionstar/. Bridge from inventable /en/brand/.",
    cta: "Open brand page",
  },
  {
    slug: "fiyat",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Prices | ARLEDSCREEN",
    h1: "LED prices",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/fiyat/.",
    cta: "Open prices",
  },
  {
    slug: "fiyatlar",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Price List | ARLEDSCREEN",
    h1: "LED price list",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/fiyatlar/.",
    cta: "Open prices",
  },
  {
    slug: "prices",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Prices | ARLEDSCREEN",
    h1: "LED prices",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/prices/.",
    cta: "Open prices",
  },
  {
    slug: "pricing",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Pricing | ARLEDSCREEN",
    h1: "LED pricing",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/pricing/.",
    cta: "Open pricing",
  },
  {
    slug: "price",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Price | ARLEDSCREEN",
    h1: "LED price",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/price/.",
    cta: "Open prices",
  },
  {
    slug: "cost",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Cost | ARLEDSCREEN",
    h1: "LED cost",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/cost/.",
    cta: "Open prices",
  },
  {
    slug: "teklif",
    target: "/en/quote/",
    title: "Quote Request | ARLEDSCREEN",
    h1: "Quote request",
    description: "EN quote hub is /en/quote/. Bridge from inventable /en/teklif/.",
    cta: "Request a quote",
  },
  {
    slug: "urunler",
    target: "/en/products/",
    title: "LED Products | ARLEDSCREEN",
    h1: "LED products",
    description: "EN products hub is /en/products/. Bridge from inventable /en/urunler/.",
    cta: "Open products",
  },
  // AI / EN shopping vocabulary → products hub (pricedPanels live under /tr/products/… Offers).
  {
    slug: "product",
    target: "/en/products/",
    title: "LED Products | ARLEDSCREEN",
    h1: "LED products",
    description: "EN products hub is /en/products/. Bridge from inventable /en/product/.",
    cta: "Open products",
  },
  {
    slug: "catalog",
    target: "/en/products/",
    title: "LED Catalog | ARLEDSCREEN",
    h1: "LED catalog",
    description:
      "Human catalog hub is /en/products/. Machine feed: /catalog.json (12 pricedPanels). Bridge from inventable /en/catalog/.",
    cta: "Open products",
  },
  {
    slug: "katalog",
    target: "/en/products/",
    title: "LED Katalog | ARLEDSCREEN",
    h1: "LED katalog",
    description: "EN products hub is /en/products/. Bridge from inventable /en/katalog/.",
    cta: "Open products",
  },
  {
    slug: "shop",
    target: "/en/products/",
    title: "LED Shop | ARLEDSCREEN",
    h1: "LED shop",
    description: "EN products hub is /en/products/. Bridge from inventable /en/shop/.",
    cta: "Open products",
  },
  {
    slug: "magaza",
    target: "/en/products/",
    title: "LED Mağaza | ARLEDSCREEN",
    h1: "LED mağaza",
    description: "EN products hub is /en/products/. Bridge from inventable /en/magaza/.",
    cta: "Open products",
  },
  {
    slug: "store",
    target: "/en/products/",
    title: "LED Store | ARLEDSCREEN",
    h1: "LED store",
    description: "EN products hub is /en/products/. Bridge from inventable /en/store/.",
    cta: "Open products",
  },
  {
    slug: "modules",
    target: "/en/products/",
    title: "LED Modules | ARLEDSCREEN",
    h1: "LED modules",
    description: "EN products hub is /en/products/. Bridge from inventable /en/modules/.",
    cta: "Open products",
  },
  {
    slug: "panel",
    target: "/en/products/",
    title: "LED Panels | ARLEDSCREEN",
    h1: "LED panels",
    description: "EN products hub is /en/products/. Bridge from inventable /en/panel/.",
    cta: "Open products",
  },
  {
    slug: "panels",
    target: "/en/products/",
    title: "LED Panels | ARLEDSCREEN",
    h1: "LED panels",
    description: "EN products hub is /en/products/. Bridge from inventable /en/panels/.",
    cta: "Open products",
  },
  {
    slug: "led-module",
    target: "/en/products/",
    title: "LED Modules | ARLEDSCREEN",
    h1: "LED modules",
    description: "EN products hub is /en/products/. Bridge from inventable /en/led-module/.",
    cta: "Open products",
  },
  {
    slug: "led-modules",
    target: "/en/products/",
    title: "LED Modules | ARLEDSCREEN",
    h1: "LED modules",
    description: "EN products hub is /en/products/. Bridge from inventable /en/led-modules/.",
    cta: "Open products",
  },
  {
    slug: "indoor-led",
    target: "/en/products/ic-mekan-led-ekran/",
    title: "Indoor LED | ARLEDSCREEN",
    h1: "Indoor LED display",
    description: "EN indoor hub is /en/products/ic-mekan-led-ekran/. Bridge from inventable /en/indoor-led/.",
    cta: "Open indoor LED",
  },
  {
    slug: "outdoor-led",
    target: "/en/products/dis-mekan-led-ekran/",
    title: "Outdoor LED | ARLEDSCREEN",
    h1: "Outdoor LED display",
    description: "EN outdoor hub is /en/products/dis-mekan-led-ekran/. Bridge from inventable /en/outdoor-led/.",
    cta: "Open outdoor LED",
  },
  {
    slug: "gob",
    target: "/en/products/gob-led-ekran/",
    title: "GOB LED | ARLEDSCREEN",
    h1: "GOB LED display",
    description: "EN GOB hub is /en/products/gob-led-ekran/. Bridge from inventable /en/gob/.",
    cta: "Open GOB LED",
  },
  {
    slug: "fine-pitch",
    target: "/en/products/ince-pitch-led-ekran/",
    title: "Fine-Pitch LED | ARLEDSCREEN",
    h1: "Fine-pitch LED display",
    description: "EN fine-pitch hub is /en/products/ince-pitch-led-ekran/. Bridge from inventable /en/fine-pitch/.",
    cta: "Open fine-pitch LED",
  },
  {
    slug: "quote-request",
    target: "/en/quote/",
    title: "Quote Request | ARLEDSCREEN",
    h1: "Quote request",
    description: "EN quote hub is /en/quote/. Bridge from inventable /en/quote-request/.",
    cta: "Request a quote",
  },
  {
    slug: "request-quote",
    target: "/en/quote/",
    title: "Request Quote | ARLEDSCREEN",
    h1: "Request a quote",
    description: "EN quote hub is /en/quote/. Bridge from inventable /en/request-quote/.",
    cta: "Request a quote",
  },
  {
    slug: "get-quote",
    target: "/en/quote/",
    title: "Get a Quote | ARLEDSCREEN",
    h1: "Get a quote",
    description: "EN quote hub is /en/quote/. Bridge from inventable /en/get-quote/.",
    cta: "Request a quote",
  },
  {
    slug: "price-list",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Price List | ARLEDSCREEN",
    h1: "LED price list",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/price-list/.",
    cta: "Open prices",
  },
  {
    slug: "pricelist",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Pricelist | ARLEDSCREEN",
    h1: "LED pricelist",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/pricelist/.",
    cta: "Open prices",
  },
  {
    slug: "led-prices",
    target: "/en/led-ekran-fiyatlari/",
    title: "LED Prices | ARLEDSCREEN",
    h1: "LED prices",
    description: "EN price hub is /en/led-ekran-fiyatlari/. Bridge from inventable /en/led-prices/.",
    cta: "Open prices",
  },
  {
    slug: "hakkimizda",
    target: "/en/about/",
    title: "About | ARLEDSCREEN",
    h1: "About",
    description: "EN about hub is /en/about/. Bridge from inventable /en/hakkimizda/.",
    cta: "Open about",
  },
  {
    slug: "about-us",
    target: "/en/about/",
    title: "About Us | ARLEDSCREEN",
    h1: "About us",
    description: "EN about hub is /en/about/. Bridge from inventable /en/about-us/.",
    cta: "Open about",
  },
  {
    slug: "company",
    target: "/en/about/",
    title: "Company | ARLEDSCREEN",
    h1: "Company",
    description: "EN about hub is /en/about/. Bridge from inventable /en/company/.",
    cta: "Open about",
  },
  {
    slug: "contact-us",
    target: "/en/contact/",
    title: "Contact Us | ARLEDSCREEN",
    h1: "Contact us",
    description: "EN contact bridge is /en/contact/ → quote hub. Bridge from inventable /en/contact-us/.",
    cta: "Open contact",
  },
  {
    slug: "kvkk",
    target: "/en/gizlilik/",
    title: "KVKK / Privacy | ARLEDSCREEN",
    h1: "KVKK / privacy",
    description: "EN privacy notice is /en/gizlilik/. Bridge from inventable /en/kvkk/.",
    cta: "Open privacy notice",
  },
  {
    slug: "privacy-policy",
    target: "/en/gizlilik/",
    title: "Privacy Policy | ARLEDSCREEN",
    h1: "Privacy policy",
    description: "EN privacy notice is /en/gizlilik/. Bridge from inventable /en/privacy-policy/.",
    cta: "Open privacy notice",
  },
  {
    slug: "cerez-politikasi",
    target: "/en/gizlilik/",
    title: "Cookie Policy | ARLEDSCREEN",
    h1: "Cookie / privacy notice",
    description: "Privacy notice is /en/gizlilik/. Bridge from inventable /en/cerez-politikasi/.",
    cta: "Open privacy notice",
  },
  {
    slug: "cookies",
    target: "/en/gizlilik/",
    title: "Cookies | ARLEDSCREEN",
    h1: "Cookies / privacy",
    description: "Privacy notice is /en/gizlilik/. Bridge from inventable /en/cookies/.",
    cta: "Open privacy notice",
  },
  {
    slug: "terms",
    target: "/en/about/",
    title: "Terms | ARLEDSCREEN",
    h1: "Terms",
    description:
      "No separate public terms page. Project terms are in written quotes. Bridge from inventable /en/terms/ to /en/about/.",
    cta: "Open about",
  },
  {
    slug: "terms-of-service",
    target: "/en/about/",
    title: "Terms of Service | ARLEDSCREEN",
    h1: "Terms of service",
    description:
      "No separate public terms page. Project terms are in written quotes. Bridge from inventable /en/terms-of-service/ to /en/about/.",
    cta: "Open about",
  },
  {
    slug: "sartlar",
    target: "/en/about/",
    title: "Şartlar | ARLEDSCREEN",
    h1: "Şartlar / terms",
    description:
      "No separate public terms page. Project terms are in written quotes. Bridge from inventable /en/sartlar/ to /en/about/.",
    cta: "Open about",
  },
];

export const EN_INVENT_BRIDGE_SLUGS = EN_INVENT_BRIDGES.map((b) => b.slug);

export function getEnInventBridge(slug: string): EnInventBridge | undefined {
  return EN_INVENT_BRIDGES.find((b) => b.slug === slug);
}

export function isEnInventBridgeSlug(slug: string): boolean {
  return EN_INVENT_BRIDGE_SLUGS.includes(slug);
}
