/**
 * TR-only <title> overrides (SEO length pass, ARL-20261009-003).
 * Keyed by canonical TR URL path. Only <title>/og:title/twitter:title change —
 * H1, body copy, JSON-LD names, prices and slugs are untouched.
 * Rule: 30–60 characters, main keyword first, brand (ARLEDSCREEN) last.
 * EN titles are owned by the EN workstream — do not add /en/ keys here.
 */
export const TR_META_TITLES: Readonly<Record<string, string>> = {
  "/tr/about/": "Hakkımızda | İstanbul LED Ekran Firması | ARLEDSCREEN",
  "/tr/avm-led-ekran/": "AVM LED Ekran | Atrium ve Cephe Ekranları | ARLEDSCREEN",
  "/tr/blog/256x128-cm-ic-mekan-led-ekran/": "256 × 128 cm İç Mekân LED Ekran Uygulaması | ARLEDSCREEN",
  "/tr/blog/alanya-white-city-resort-hotel-led-ekran/": "Alanya White City Resort Hotel LED Ekranı | ARLEDSCREEN",
  "/tr/blog/eskisehir-sigorta-subesi-led-ekran/": "Eskişehir Sigorta Şubesi LED Ekran Uygulaması | ARLEDSCREEN",
  "/tr/blog/ic-mekan-led-ekran-ile-markanizi-gorunur-kilin/": "İç Mekân LED Ekranla Markanızı Görünür Kılın | ARLEDSCREEN",
  "/tr/blog/unye-belediyesi-384x160-p3-led-ekran/": "Ünye Belediyesi 384 × 160 cm P3 LED Ekran | ARLEDSCREEN",
  "/tr/bolgeler/istanbul/": "LED Ekran İstanbul | Satış, Kurulum, Servis | ARLEDSCREEN",
  "/tr/cephe-led-ekran/": "Cephe LED Ekran | Dış Mekân Bina Ekranları | ARLEDSCREEN",
  "/tr/fuar-led-ekran/": "Fuar LED Ekran | Stant ve Etkinlik Ekranları | ARLEDSCREEN",
  "/tr/hesaplayici/": "LED Ekran Fiyat Hesaplayıcı | Maliyet Hesabı | ARLEDSCREEN",
  "/tr/led-ekran-fiyatlari/": "LED Ekran Fiyatları 2026 | Panel Fiyat Listesi | ARLEDSCREEN",
  "/tr/otel-led-ekran/": "Otel LED Ekran | Lobi ve Cephe Ekranları | ARLEDSCREEN",
  "/tr/p1-25-led-ekran/": "P1.25 LED Ekran | İnce Pitch GOB Panel | ARLEDSCREEN",
  "/tr/p1-86-led-ekran/": "P1.86 LED Ekran | İnce Pitch, GOB ve Esnek | ARLEDSCREEN",
  "/tr/p2-5-led-ekran/": "P2.5 LED Ekran | İç ve Dış Mekân Modeller | ARLEDSCREEN",
  "/tr/p2-9-led-ekran/": "P2.9 LED Ekran | Dış Mekân Orta Mesafe | ARLEDSCREEN",
  "/tr/p3-07-led-ekran/": "P3.07 LED Ekran | İç ve Dış Mekân Orta Mesafe | ARLEDSCREEN",
  "/tr/p4-led-ekran/": "P4 LED Ekran | Cephe ve Dış Mekân | ARLEDSCREEN",
  "/tr/p5-led-ekran/": "P5 LED Ekran | Uzak Mesafe Dış Mekân | ARLEDSCREEN",
  "/tr/products/colorlight-kontrolculer/s20/": "Colorlight S20 LED Gönderici Kart | ARLEDSCREEN",
  "/tr/products/colorlight-kontrolculer/vx20/": "Colorlight VX20 Video İşlemci | ARLEDSCREEN",
  "/tr/products/colorlight-kontrolculer/x20/": "Colorlight X20 Multimedya LED İşlemci | ARLEDSCREEN",
  "/tr/products/colorlight-kontrolculer/x40m/": "Colorlight X40m Yüksek Yük LED İşlemci | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/": "Dış Mekân LED Ekran Fiyatları ve Modelleri | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p2-5/": "P2.5 Dış Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p2-9/": "P2.9 Dış Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p3-07/": "P3.07 Dış Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p4-on-servis/": "P4 Önden Servisli Dış Mekân LED Modül Fiyatı | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p4/": "P4 Dış Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p5/": "P5 Dış Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/dis-mekan-led-ekran/p8/": "P8 Dış Mekân LED Modül | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/esnek-led-ekran/p1-86-esnek/": "P1.86 Esnek LED Ekran Modülü | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/esnek-led-ekran/p2-5-esnek/": "P2.5 Esnek LED Ekran Modülü | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/gob-led-ekran/": "GOB LED Ekran Fiyatları ve Modelleri | ARLEDSCREEN",
  "/tr/products/gob-led-ekran/p1-25-gob/": "P1.25 GOB İç Mekân LED Modül Fiyatı | ARLEDSCREEN",
  "/tr/products/gob-led-ekran/p1-53-gob/": "P1.53 GOB İç Mekân LED Modül Fiyatı | ARLEDSCREEN",
  "/tr/products/gob-led-ekran/p1-86-gob/": "P1.86 GOB İç Mekân LED Modül Fiyatı | ARLEDSCREEN",
  "/tr/products/huidu-kontrol-kartlari/hd-a7/": "Huidu HD-A7 4K Çift Mod LED Kontrolcü | ARLEDSCREEN",
  "/tr/products/huidu-kontrol-kartlari/hd-c16/": "Huidu HD-C16 Asenkron LED Kontrol Kartı | ARLEDSCREEN",
  "/tr/products/huidu-kontrol-kartlari/hd-w60/": "Huidu HD-W60 Wi-Fi LED Kontrol Kartı | ARLEDSCREEN",
  "/tr/products/ic-mekan-led-ekran/": "İç Mekân LED Ekran Fiyatları ve Modelleri | ARLEDSCREEN",
  "/tr/products/ic-mekan-led-ekran/p2-5/": "P2.5 İç Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/ic-mekan-led-ekran/p3-07/": "P3.07 İç Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/ic-mekan-led-ekran/p4/": "P4 İç Mekân LED Modül Fiyatı | NXTIONSTAR | ARLEDSCREEN",
  "/tr/products/ince-pitch-led-ekran/": "İnce Pitch LED Ekran | Toplantı ve Stüdyo | ARLEDSCREEN",
  "/tr/products/led-modul-ve-kontrol-sistemleri/": "LED Modül ve Kontrol Sistemleri | ARLEDSCREEN",
  "/tr/products/novastar-kontrolculer/": "NovaStar Kontrolcü Satış ve Kurulum | ARLEDSCREEN",
  "/tr/products/novastar-kontrolculer/mctrl660-pro/": "NovaStar MCTRL660 PRO Gönderici Kart | ARLEDSCREEN",
  "/tr/products/novastar-kontrolculer/tb50/": "NovaStar Taurus TB50 Multimedya Oynatıcı | ARLEDSCREEN",
  "/tr/products/novastar-kontrolculer/vx600/": "NovaStar VX600 All-in-One LED Kontrolcü | ARLEDSCREEN",
  "/tr/products/poster-led-ekran/": "Poster ve Totem LED Ekran | Ayaklı Ekran | ARLEDSCREEN",
  "/tr/projelerimiz/beylikduzu-belediyesi-led-ekran/": "Beylikdüzü Belediyesi LED Ekran Projesi | ARLEDSCREEN",
  "/tr/projelerimiz/beylikduzu-yasam-cafe-led-ekran/": "Beylikdüzü Yaşam Cafe LED Ekran Projesi | ARLEDSCREEN",
  "/tr/projelerimiz/istanbul-drama-sanat-atolyesi-led-ekran/": "İstanbul Drama Sanat Atölyesi LED Ekranı | ARLEDSCREEN",
  "/tr/projelerimiz/manisa-buyuksehir-belediyesi-led-ekran/": "Manisa Büyükşehir Belediyesi LED Ekranı | ARLEDSCREEN",
  "/tr/projelerimiz/orta-sekerli-kampus-caffe-lounge-led-ekran/": "Orta Şekerli Kampüs Caffe Lounge LED Ekranı | ARLEDSCREEN",
  "/tr/projelerimiz/orta-sekerli-kentpark-cafe-led-ekran/": "Orta Şekerli Kentpark Cafe LED Ekran Projesi | ARLEDSCREEN",
  "/tr/projelerimiz/sinan-polat-sigorta-led-ekran/": "Sinan Polat Sigorta LED Ekran Projesi | ARLEDSCREEN",
  "/tr/projelerimiz/unye-belediyesi-ordu-gunleri-led-ekran/": "Ünye Belediyesi Ordu Günleri LED Ekranı | ARLEDSCREEN",
  "/tr/projelerimiz/white-city-resort-hotel-led-ekran/": "White City Resort Hotel LED Ekran Projesi | ARLEDSCREEN",
  "/tr/rehber/gob-vs-smd/": "GOB vs SMD LED Ekran: Farklar ve Seçim | ARLEDSCREEN",
  "/tr/rehber/kiosk-dijital-ekran/": "Kiosk Dijital Ekran | Dokunmatik Bilgi Noktası | ARLEDSCREEN",
  "/tr/rehber/kiralik-mi-satin-alma/": "Kiralık LED Ekran mı, Satın Alma mı? | ARLEDSCREEN",
  "/tr/rehber/led-tabela-mi-led-ekran-mi/": "LED Tabela mı, LED Ekran mı? Dijital Ekran | ARLEDSCREEN",
  "/tr/rehber/piksel-araligi-secimi/": "İç Mekân LED Ekranda Piksel Aralığı Seçimi | ARLEDSCREEN",
  "/tr/sahne-led-ekran/": "Sahne LED Ekran | Konser ve Etkinlik | ARLEDSCREEN",
  "/tr/sss/": "LED Ekran Sık Sorulan Sorular | Fiyat, Montaj | ARLEDSCREEN",
  "/tr/totem-led-ekran/": "Totem LED Ekran | Ayaklı Dijital Ekran | ARLEDSCREEN",
};

/** Returns the TR override for a canonical TR path ("/tr/…/"), else the fallback title. */
export function trMetaTitle(trPath: string, fallback: string): string {
  return TR_META_TITLES[trPath] ?? fallback;
}
